//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int id { get; set; }
        public string UrunNo { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    }
}
